# automatically pull in upstream

name: Merge upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 9 * * 1'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Enrico Z. Borba'
          git config --global user.email 'enricozb@gmail.com'

          git pull --unshallow

          git remote add upstream https://github.com/dbcli/pgcli.git
          git fetch upstream

          git checkout master
          git merge --no-edit upstream/master
          git push origin master  
